from pathlib import Path
import textwrap

import fitz

from app.schemas.answer import Answer, AnswerStatus, Citation
from app.schemas.question import RfpQuestion

EXPORTABLE_STATUSES = {AnswerStatus.approved, AnswerStatus.edited}
PAGE_WIDTH = 595
PAGE_HEIGHT = 842
MARGIN = 56
LINE_HEIGHT = 15


def export_project_to_pdf(
    project_name: str,
    questions: list[RfpQuestion],
    answers_by_question_id: dict[str, Answer],
    citations_by_answer_id: dict[str, list[Citation]],
    output_path: Path,
) -> int:
    """Export approved/edited answers to a PDF file using reviewed final text."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = fitz.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
    y = MARGIN

    def add_page() -> None:
        nonlocal page, y
        page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
        y = MARGIN

    def write_line(text: str, font_size: int = 11, bold: bool = False, indent: int = 0) -> None:
        nonlocal y
        if y > PAGE_HEIGHT - MARGIN:
            add_page()
        page.insert_text(
            (MARGIN + indent, y),
            text,
            fontsize=font_size,
            fontname="helv",
            color=(0.08, 0.09, 0.12),
        )
        y += LINE_HEIGHT if font_size <= 11 else LINE_HEIGHT + 5

    def write_wrapped(text: str, font_size: int = 11, bold: bool = False, indent: int = 0) -> None:
        max_width = 88 if indent == 0 else 80
        for paragraph in text.splitlines() or [""]:
            if not paragraph.strip():
                write_line("", font_size=font_size, indent=indent)
                continue
            for line in textwrap.wrap(paragraph, width=max_width):
                write_line(line, font_size=font_size, bold=bold, indent=indent)

    write_wrapped(project_name, font_size=18, bold=True)
    write_wrapped("Generated by Serbian Vibe RFP. Only reviewed answers are included.")
    y += 12

    exported_count = 0
    for question in sorted(questions, key=lambda q: q.order_index):
        answer = answers_by_question_id.get(question.id)
        if not answer or answer.status not in EXPORTABLE_STATUSES:
            continue

        exported_count += 1
        write_wrapped(question.question_text, font_size=13, bold=True)
        y += 4
        write_wrapped(answer.final_text)

        citations = citations_by_answer_id.get(answer.id, [])
        if citations:
            y += 6
            write_line("Sources:", bold=True)
            for citation in citations:
                source = citation.document_title
                if citation.section_title:
                    source += f", {citation.section_title}"
                if citation.page_number is not None:
                    source += f", page {citation.page_number}"
                write_wrapped(f"- {source}", font_size=10, indent=12)
        y += 16

    doc.save(output_path)
    doc.close()
    return exported_count
