from pathlib import Path

from docx import Document as DocxDocument

from app.schemas.answer import Answer, AnswerStatus, Citation
from app.schemas.question import RfpQuestion

EXPORTABLE_STATUSES = {AnswerStatus.approved, AnswerStatus.edited}


def export_project_to_docx(
    project_name: str,
    questions: list[RfpQuestion],
    answers_by_question_id: dict[str, Answer],
    citations_by_answer_id: dict[str, list[Citation]],
    output_path: Path,
) -> int:
    """Export approved/edited answers to a DOCX file.

    The export intentionally uses `final_text`, not `draft_text`.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = DocxDocument()
    doc.add_heading(project_name, level=0)
    doc.add_paragraph("Generated by RFP Copilot. Only reviewed answers are included.")

    exported_count = 0
    for question in sorted(questions, key=lambda q: q.order_index):
        answer = answers_by_question_id.get(question.id)
        if not answer or answer.status not in EXPORTABLE_STATUSES:
            continue

        exported_count += 1
        doc.add_heading(question.question_text, level=1)
        doc.add_paragraph(answer.final_text)

        citations = citations_by_answer_id.get(answer.id, [])
        if citations:
            doc.add_paragraph("Sources:")
            for citation in citations:
                source = citation.document_title
                if citation.section_title:
                    source += f", {citation.section_title}"
                if citation.page_number is not None:
                    source += f", page {citation.page_number}"
                doc.add_paragraph(source, style="List Bullet")

    doc.save(output_path)
    return exported_count
